name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install go-task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: release
        run: task release

      - name: Upload archives to the GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
